import type { Service, ServiceCategory } from './types';

const createdAt = '2026-09-30T00:00:00.000Z';

export const sampleCategories: ServiceCategory[] = [
  { id: 'plumbing', name: 'Plumbing', slug: 'plumbing', icon: 'Droplets', description: 'Leaks, fixtures, and pipe repairs', display_order: 1, image_url: 'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?auto=format&fit=crop&w=960&q=80', created_at: createdAt },
  { id: 'electrical', name: 'Electrical', slug: 'electrical', icon: 'Zap', description: 'Safe electrical repair and installation', display_order: 2, image_url: 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?auto=format&fit=crop&w=960&q=80', created_at: createdAt },
  { id: 'carpentry', name: 'Carpentry', slug: 'carpentry', icon: 'Hammer', description: 'Furniture and woodwork repairs', display_order: 3, image_url: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=960&q=80', created_at: createdAt },
  { id: 'appliance-repair', name: 'Appliance Repair', slug: 'appliance-repair', icon: 'Wrench', description: 'Home appliance diagnosis and repair', display_order: 4, image_url: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=960&q=80', created_at: createdAt },
  { id: 'cleaning', name: 'Cleaning', slug: 'cleaning', icon: 'Sparkles', description: 'Regular and deep home cleaning', display_order: 5, image_url: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=960&q=80', created_at: createdAt },
  { id: 'painting', name: 'Painting', slug: 'painting', icon: 'Paintbrush', description: 'Interior painting and touch-ups', display_order: 6, image_url: 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?auto=format&fit=crop&w=960&q=80', created_at: createdAt },
];

const serviceRows: Omit<Service, 'category'>[] = [
  { id: 'plumbing-leak-repair', category_id: 'plumbing', name: 'Leak & Pipe Repair', slug: 'leak-pipe-repair', description: 'Find and repair common pipe, tap, and fixture leaks.', pricing_type: 'flat', base_price: 399, unit_label: null, estimated_duration_mins: 60, icon: 'Droplets', image_url: sampleCategories[0].image_url, is_active: true, is_sample: true, created_at: createdAt },
  { id: 'plumbing-fixture-install', category_id: 'plumbing', name: 'Fixture Installation', slug: 'fixture-installation', description: 'Install or replace taps, shower heads, and basic fittings.', pricing_type: 'flat', base_price: 599, unit_label: null, estimated_duration_mins: 90, icon: 'Wrench', image_url: sampleCategories[0].image_url, is_active: true, is_sample: true, created_at: createdAt },
  { id: 'electrical-repair', category_id: 'electrical', name: 'Electrical Repair', slug: 'electrical-repair', description: 'Troubleshoot switches, outlets, and common household faults.', pricing_type: 'flat', base_price: 449, unit_label: null, estimated_duration_mins: 60, icon: 'Zap', image_url: sampleCategories[1].image_url, is_active: true, is_sample: true, created_at: createdAt },
  { id: 'light-installation', category_id: 'electrical', name: 'Light Installation', slug: 'light-installation', description: 'Install or replace indoor lights and ceiling fixtures.', pricing_type: 'flat', base_price: 499, unit_label: null, estimated_duration_mins: 60, icon: 'Lightbulb', image_url: sampleCategories[1].image_url, is_active: true, is_sample: true, created_at: createdAt },
  { id: 'furniture-repair', category_id: 'carpentry', name: 'Furniture Repair', slug: 'furniture-repair', description: 'Repair loose joints, drawers, hinges, and everyday furniture damage.', pricing_type: 'hourly', base_price: 500, unit_label: 'hour', estimated_duration_mins: 90, icon: 'Hammer', image_url: sampleCategories[2].image_url, is_active: true, is_sample: true, created_at: createdAt },
  { id: 'shelf-installation', category_id: 'carpentry', name: 'Shelf & Fitting Installation', slug: 'shelf-installation', description: 'Install shelves, curtain rails, and simple wall fittings.', pricing_type: 'flat', base_price: 699, unit_label: null, estimated_duration_mins: 90, icon: 'PanelsTopLeft', image_url: sampleCategories[2].image_url, is_active: true, is_sample: true, created_at: createdAt },
  { id: 'appliance-diagnosis', category_id: 'appliance-repair', name: 'Appliance Diagnosis', slug: 'appliance-diagnosis', description: 'Diagnose common refrigerator, washer, and kitchen appliance issues.', pricing_type: 'flat', base_price: 499, unit_label: null, estimated_duration_mins: 60, icon: 'Wrench', image_url: sampleCategories[3].image_url, is_active: true, is_sample: true, created_at: createdAt },
  { id: 'air-conditioner-service', category_id: 'appliance-repair', name: 'Air Conditioner Service', slug: 'air-conditioner-service', description: 'Routine inspection and cleaning for a home air conditioner.', pricing_type: 'flat', base_price: 899, unit_label: null, estimated_duration_mins: 90, icon: 'Wind', image_url: sampleCategories[3].image_url, is_active: true, is_sample: true, created_at: createdAt },
  { id: 'home-cleaning', category_id: 'cleaning', name: 'Home Cleaning', slug: 'home-cleaning', description: 'A focused clean for kitchens, bathrooms, and living spaces.', pricing_type: 'hourly', base_price: 350, unit_label: 'hour', estimated_duration_mins: 120, icon: 'Sparkles', image_url: sampleCategories[4].image_url, is_active: true, is_sample: true, created_at: createdAt },
  { id: 'deep-cleaning', category_id: 'cleaning', name: 'Deep Cleaning', slug: 'deep-cleaning', description: 'Detailed cleaning for built-up dust and hard-to-reach areas.', pricing_type: 'hourly', base_price: 450, unit_label: 'hour', estimated_duration_mins: 180, icon: 'Sparkles', image_url: sampleCategories[4].image_url, is_active: true, is_sample: true, created_at: createdAt },
  { id: 'interior-painting', category_id: 'painting', name: 'Interior Painting', slug: 'interior-painting', description: 'Small-room and touch-up painting; materials quoted separately.', pricing_type: 'unit', base_price: 25, unit_label: 'sq ft', estimated_duration_mins: 240, icon: 'Paintbrush', image_url: sampleCategories[5].image_url, is_active: true, is_sample: true, created_at: createdAt },
  { id: 'wall-touch-up', category_id: 'painting', name: 'Wall Touch-Up', slug: 'wall-touch-up', description: 'Patch and repaint small scuffs and damaged wall areas.', pricing_type: 'flat', base_price: 599, unit_label: null, estimated_duration_mins: 90, icon: 'Paintbrush', image_url: sampleCategories[5].image_url, is_active: true, is_sample: true, created_at: createdAt },
];

export const sampleServices: Service[] = serviceRows.map((service) => ({
  ...service,
  category: sampleCategories.find((category) => category.id === service.category_id),
}));